#pragma once

#ifndef WITH_EDITOR
#define WITH_EDITOR 0
#endif

#define  PLATFORM_RHITHREAD_DEFAULT_BYPASS WITH_EDITOR

#define  PLATFORM_64BITS 1
#define  PLATFORM_HAS_64BIT_ATOMICS 1
#define  PLATFORM_HAS_128BIT_ATOMICS 0
#define  PLATFORM_MAC 0
